# Generated by Django 3.1 on 2020-09-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='videos',
            new_name='video',
        ),
    ]
