# Generated by Django 3.1 on 2020-09-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
