# Generated by Django 3.1 on 2020-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20200903_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='videos.Pricing'),
        ),
    ]
