# Generated by Django 3.1 on 2020-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20200905_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
