# Generated by Django 3.1 on 2020-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_pricing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
